### ISSUE TITLE
Incompatible with python 3.12: the `imp` library is deprecated in favour of `importlib`

### ISSUE THREAD

**Issue by connortann** [sitkatech/pypatch#2]
Thanks for the useful package! A quick bug report..

The library uses a deprecated builtin module `imp`, which does not exist in python 3.12 and above:

https://github.com/sitkatech/pypatch/blob/2a0b0449ede8e70e4c5997e8287b865f3eaa7663/Source/pypatch/command.py#L87

This should be replaced with `importlib`.

**Comment by andyphenix** [comment]
Fixed in 1.0.2
